### PR TITLE
Add 16px icon

### PR DESCRIPTION
**Pull request by erayd**
Add 16px icon from #10.

### CODE REVIEW

**Comment by erayd** [comment]
@532910 Thank you for doing this :-). Could you please provide a version of this icon with a transparent background, rather than the black background used in #10 - the black background doesn't comply with webstore policy, and looks kinda strange.

**Comment by 532910** [comment]
https://github.com/browserpass/browserpass-otp/issues/10 updated

**Comment by erayd** [comment]
Committed directly in master - no merge necessary.

**Comment by 532910** [comment]
Looks good, than you! (:

**Comment by erayd** [comment]
Thank you - you created the icon, after all! :1st_place_medal:

**Pull request closed without merging**
